export const GET_SEARCH_REQUEST = "GET_SEARCH_REQUEST";
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_FAILED = "GET_SEARCH_FAILED";

export const GET_MORE_SEARCH_REQUEST = "GET_MORE_SEARCH_REQUEST";
export const GET_MORE_SEARCH_SUCCESS = "GET_MORE_SEARCH_SUCCESS";
export const GET_MORE_SEARCH_FAILED = "GET_MORE_SEARCH_FAILED";
